baseurl: "https://xianghuang.me/"
languageCode: "en-us"
title: "Xiang Huang | 黄湘"
theme: "hugo-ivy"
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 10

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "Todo"
      url: "/todo/"
      weight: 5
    - name: "中文"
      url: "/cn/"
      weight: 6
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "孩童"
      url: "/cn/kids/"
      weight: 5
    - name: "事务"
      url: "/todo/"
      weight: 6
    - name: "English"
      url: "/en/"
      weight: 7

params:
  description: "Personal website of Xiang; 黄湘的个人网站"
  footer: "&copy; [Xiang Huang](/) 2023 - {Year}"
  customJS:
    - "comment-utils.js"
    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
    - "external-link.js"
    - "alt-title.js"
    - "header-link.js"
  githubContentURL: "https://github.com/xiangyazi24/me/tree/master/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "11.7.0"
  highlightjsLang: ["latex"]
  highlightjsTheme: "base16/heetch-light"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Xiang Huang"
      tag: ""

  author:
    en: "Xiang Huang"
    cn: "黄湘"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  highlight:
    codeFences: true
    style: monokai
    anchorLineNos: false

  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
