baseurl: "https://xianghuang.me/"
languageCode: "en-us"
title: "Xiang Huang | 黄湘"
theme: "hugo-ivy"
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↑"
rssLimit: 10

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "English"
      url: "/en/"
      weight: 1
    - name: "Math ∩ CS"
      url: "/math/"
      weight: 2
    - name: "Quantum"
      url: "/quantum/"
      weight: 3
    - name: "Course Notes"
      url: "/course/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
    - name: "Homepage"
      url: "/"
      weight: 6
  en:

    - name: "English"
      url: "/en/"
      weight: 1
    - name: "Math ∩ CS"
      url: "/math/"
      weight: 2
    - name: "Quantum"
      url: "/quantum/"
      weight: 3
    - name: "Course Notes"
      url: "/course/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
    - name: "Homepage"
      url: "/"
      weight: 6
  cn:
    - name: "English"
      url: "/en/"
      weight: 1
    - name: "Math ∩ CS"
      url: "/math/"
      weight: 2
    - name: "Quantum"
      url: "/quantum/"
      weight: 3
    - name: "Course Notes"
      url: "/course/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
    - name: "Homepage"
      url: "/"
      weight: 6

  Math:

    - name: "English"
      url: "/en/"
      weight: 1
    - name: "Math ∩ CS"
      url: "/math/"
      weight: 2
    - name: "Quantum"
      url: "/quantum/"
      weight: 3
    - name: "Course Notes"
      url: "/course/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
    - name: "Homepage"
      url: "/"
      weight: 6

  Quantum:

    - name: "English"
      url: "/en/"
      weight: 1
    - name: "Math ∩ CS"
      url: "/math/"
      weight: 2
    - name: "Quantum"
      url: "/quantum/"
      weight: 3
    - name: "Course Notes"
      url: "/course/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
    - name: "Homepage"
      url: "/"
      weight: 6

params:
  description: "Personal website of Xiang; 黄湘的个人网站"
  footer: "&copy; [Xiang Huang](/) 2023 - {Year}"
  customJS:
    - "comment-utils.js"
    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
    - "external-link.js"
    - "alt-title.js"
    - "header-link.js"
  githubContentURL: "https://github.com/xiangyazi24/me/tree/master/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme), no longer use highlight!

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Xiang Huang"
      tag: ""

  author:
    en: "Xiang Huang"
    cn: "黄湘"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"


markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
